/* =========================================================================
   CANIS HÆMATICA – Blutwerte-Atlas des Hundes
   Datensatz: Kategorien, Organe, Rassen-/Alters-/Geschlechts-Modifikatoren,
   Parameter (Referenz, Bedeutung, Organ-/Stoffwechselbezug, ↑/↓, Erkrankungen,
   "Was untersuchen?") und Leitbefund-Muster.

   WICHTIG: Referenzbereiche sind orientierende, gerätе-/laborabhängige Werte
   (Hund, adult). Maßgeblich ist IMMER der Referenzbereich des eigenen Labors.
   Diese App ist ein Lern- und Nachschlagewerk und ersetzt KEINE tierärztliche
   Diagnose oder Behandlung.
   ========================================================================= */

/* ---------- KATEGORIEN (Farbcodierung wie Canis Metabolica) ---------- */
const CATEGORIES = {
  ery:      { name: "Rote Reihe (Erythrozyten)",       short:"Rote Reihe",   color:"#ff4d4d", rgb:"255,77,77" },
  leuko:    { name: "Weiße Reihe (Leukozyten)",        short:"Weiße Reihe",  color:"#00f2fe", rgb:"0,242,254" },
  thrombo:  { name: "Thrombozyten & Gerinnung",        short:"Gerinnung",    color:"#f35588", rgb:"243,85,136" },
  leber:    { name: "Leber & Galle",                   short:"Leber",        color:"#ffd166", rgb:"255,209,102" },
  niere:    { name: "Niere & Harn",                    short:"Niere",        color:"#00ff87", rgb:"0,255,135" },
  elektro:  { name: "Elektrolyte & Säure-Basen",       short:"Elektrolyte",  color:"#00e5ff", rgb:"0,229,255" },
  protein:  { name: "Proteine",                        short:"Proteine",     color:"#9d4edd", rgb:"157,78,221" },
  stoff:    { name: "Zucker & Fett (Metabolismus)",    short:"Zucker/Fett",  color:"#ff8c00", rgb:"255,140,0" },
  enzym:    { name: "Muskel- & Pankreas-Enzyme",       short:"Enzyme",       color:"#4dd4ff", rgb:"77,212,255" },
  endokrin: { name: "Hormone (Endokrin)",              short:"Hormone",      color:"#ffa6c9", rgb:"255,166,201" },
  spezial:  { name: "Entzündung & Spezialmarker",      short:"Spezial",      color:"#a3e635", rgb:"163,230,53" }
};

/* ---------- ORGANE (für die Organ-Karte) ----------
   x,y direkt in viewBox-Einheiten (0–100 / 0–78). lp = Label oben(-1)/unten(+1). */
const ORGANS = {
  schilddruese: { name:"Schilddrüse",  icon:"🦋", desc:"Steuert den Grundumsatz über T4/fT4 (Regelkreis mit TSH).", x:34, y:30, lp:-1 },
  knochenmark:  { name:"Knochenmark",  icon:"🦴", desc:"Bildet alle Blutzellen (Hämatopoese): rote/weiße Reihe und Thrombozyten.", x:50, y:26, lp:-1 },
  herz:         { name:"Herz",         icon:"❤️", desc:"Taurin-/Carnitin-abhängiger Muskel; CK und Troponin steigen bei Schaden, DCM bei Taurinmangel.", x:33, y:38, lp:1 },
  leber:        { name:"Leber",        icon:"🫀", desc:"Zentrales Stoffwechselorgan: Eiweißsynthese (Albumin, Gerinnungsfaktoren), Entgiftung (Ammoniak→Harnstoff), Galle, Glucose-Haushalt.", x:44, y:44, lp:1 },
  gallenwege:   { name:"Gallenwege",   icon:"🟡", desc:"Abfluss der Galle. Stau (Cholestase) hebt ALP, GGT und Bilirubin.", x:40, y:52, lp:1 },
  milz:         { name:"Milz",         icon:"🟥", desc:"Blutspeicher und Abbau alter Erythrozyten; bei Sport/Stress Kontraktion → kurzfristig höherer Hämatokrit.", x:55, y:38, lp:-1 },
  pankreas:     { name:"Bauchspeicheldrüse", map:"Pankreas", icon:"🔶", desc:"Verdauungsenzyme (Lipase, Amylase) und Insulin/Glukagon (Blutzucker).", x:53, y:50, lp:1 },
  darm:         { name:"Darm",         icon:"🌀", desc:"Aufnahme von Nährstoffen, Eiweiß und Arginin; Verluste bei Enteropathie senken Albumin/Globulin.", x:62, y:50, lp:1 },
  niere:        { name:"Niere",        icon:"🫘", desc:"Filtert Harnstoff/Kreatinin/SDMA, reguliert Elektrolyte, Wasser, Säure-Basen und Erythropoetin (Ery-Bildung).", x:68, y:36, lp:-1 },
  nebenniere:   { name:"Nebenniere",   icon:"🔺", desc:"Bildet Cortisol (Stress) und Aldosteron (Na/K). Cushing = zu viel, Addison = zu wenig.", x:76, y:42, lp:1 },
  muskel:       { name:"Skelettmuskel",icon:"💪", desc:"Quelle von CK und (mit) AST; liefert Kreatinin proportional zur Muskelmasse.", x:22, y:50, lp:1 },
  gefaess:      { name:"Gefäße & Plasma", map:"Plasma", icon:"🩸", desc:"Transportraum: Hydratation verändert fast alle Konzentrationen (Eindickung/Verdünnung).", x:85, y:48, lp:-1 }
};

/* ---------- RASSEN-/STATUS-MODIFIKATOREN ----------
   Verändern die angezeigte Interpretation. 'affects' nennt betroffene Parameter. */
const BREEDS = {
  standard:  { name:"Standard (adult, mittelgroß)", note:"Allgemeine adulte Referenz." },
  windhund:  { name:"Windhund (Greyhound, Whippet, Galgo …)",
    note:"Sight Hounds haben rasse-eigene Referenzwerte: HKT, Erythrozyten & Hämoglobin deutlich HÖHER (Sauerstofftransport), dafür Leukozyten & Thrombozyten NIEDRIGER, Kreatinin höher (Muskelmasse), T4 & TSH niedriger, Gesamtprotein eher niedrig.",
    affects:{hkt:"höher (bis ~65 %)", rbc:"höher", hb:"höher", wbc:"niedriger", thrombozyten:"niedriger (oft 100–200)", kreatinin:"höher (Muskelmasse)", t4:"niedriger", tsh:"niedriger", gesamtprotein:"eher niedrig"} },
  akita:     { name:"Akita / Shiba / japan. Rassen",
    note:"Tragen z. T. viel Kalium IN den Erythrozyten (HK-Typ). Bei Hämolyse der Probe → falsch hohes Kalium (Pseudohyperkaliämie). Außerdem oft kleinere Erythrozyten (niedriges MCV) als Normvariante.",
    affects:{kalium:"Messung falsch hoch bei Hämolyse", mcv:"physiologisch niedriger"} },
  dalmatiner:{ name:"Dalmatiner",
    note:"SLC2A9-Defekt: Harnsäure wird kaum zu Allantoin abgebaut → höhere Harnsäure, Risiko für Ammoniumurat-Steine.",
    affects:{} },
  cavalier:  { name:"Cavalier King Charles & verwandte",
    note:"Erbliche Makrothrombozytopenie: Automaten zählen die großen Plättchen nicht → 'falsch' niedrige Thrombozyten bei gesundem Tier. MPV hoch. Immer Ausstrich kontrollieren.",
    affects:{thrombozyten:"automatisch falsch niedrig (Makroplättchen)", mpv:"hoch"} },
  dobermann: { name:"Dobermann / Boxer / Pinscher",
    note:"Erhöhtes Risiko für von-Willebrand-Erkrankung (vWF niedrig) und für DCM (Herz). Gerinnung vor OP prüfen.",
    affects:{vwf:"oft niedrig (vWD)"} },
  welpe:     { name:"Welpe / Junghund (<6–12 Mon.)",
    note:"Wachstum verändert vieles: ALP & Phosphat HÖHER (Knochenwachstum), Albumin & Gesamtprotein niedriger, Cholesterin niedriger, Erythrozyten/HKT bis ~8–12 Wo. niedriger ('Welpenanämie'), Glucose-Reserven klein (Hypoglykämie-Risiko).",
    affects:{alp:"physiologisch deutlich höher", phosphat:"höher (Wachstum)", albumin:"niedriger", hkt:"niedriger (bis ~3 Mon.)", cholesterin:"niedriger", glucose:"instabiler"} },
  senior:    { name:"Senior (>7–8 J., großrassig früher)",
    note:"Häufiger Begleitbefunde: leicht steigendes SDMA/Kreatinin, niedrigeres T4, mehr Komorbiditäten. Werte stets im Verlauf bewerten.",
    affects:{sdma:"tendenziell höher", t4:"tendenziell niedriger"} },
  traechtig: { name:"Trächtig / laktierend",
    note:"Physiologische Verdünnungsanämie (HKT niedriger), Alkalische Phosphatase & Cholesterin steigen, Calcium kann um die Geburt stark fallen (Eklampsie-Risiko bei kleinen Rassen).",
    affects:{hkt:"niedriger (Verdünnung)", calcium:"Abfall-Risiko peripartal", alp:"höher", cholesterin:"höher", glucose:"Hypoglykämie-Risiko"} },
  klein:     { name:"Toy-/Zwergrasse (Chihuahua, Yorkie …)",
    note:"Kleine Glykogen-/Energiereserven → Hypoglykämie-Risiko (Welpen, Fasten, Stress). Portosystemischer Shunt häufiger (Yorkshire) → niedriger Harnstoff/Albumin, hohe Gallensäuren/Ammoniak.",
    affects:{glucose:"Hypoglykämie-Risiko", gallensaeuren:"bei Shunt hoch", ammoniak:"bei Shunt hoch"} }
};

const REGION_NOTE =
  "„Region“ wirkt v. a. über (1) das jeweilige Labor/Analysegerät – Referenzbereiche sind gerätespezifisch und nicht 1:1 übertragbar; " +
  "(2) Höhenlage – in großer Höhe steigen Erythrozyten/HKT/Hämoglobin kompensatorisch; " +
  "(3) endemische Erkrankungen – z. B. Mittelmeerraum (Leishmaniose → Hyperglobulinämie, Anämie, Proteinurie), " +
  "Zecken-/Reisekrankheiten (Ehrlichiose, Babesiose, Anaplasmose → Thrombozytopenie, Anämie), Herzwurm in warmen Regionen. " +
  "Es gibt daher keine starre „Tabelle pro Land“ – nutze lokale Laborwerte und denke an regionale Differenzialdiagnosen.";

/* ---------- PARAMETER (Blutwerte) ---------- */
/* Felder: name, abbr, cat, unit, unitSI, ref{lo,hi,txt}, organs[], pathway,
   formula?, meaning, high[], low[], diseases[], next, modNote? */
const PARAMS = {

  /* ===================== ROTE REIHE ===================== */
  hkt: { name:"Hämatokrit (HKT/PCV)", abbr:"HKT", cat:"ery", unit:"%", ref:{lo:37,hi:55,txt:"37–55 %"},
    organs:["knochenmark","niere","milz","gefaess"], pathway:"Sauerstofftransport; Bildung erythropoetin-abhängig (Niere)",
    meaning:"Volumenanteil der roten Blutkörperchen am Blut. Wichtigster Schnellwert für Anämie vs. Eindickung.",
    high:["Dehydratation/Eindickung (häufigste Ursache)","Milzkontraktion (Stress, Sport, Windhund)","Polyzythämie (selten, z. B. EPO-Tumor)","Höhenlage"],
    low:["Anämie: Blutverlust, Hämolyse oder verminderte Bildung","Chronische Niereninsuffizienz (EPO↓)","Entzündung/Tumor (Anemia of chronic disease)","Verdünnung (Infusion, Trächtigkeit)"],
    diseases:["Anämie","Blutung/Trauma","IMHA (immunhämolytische Anämie)","CNI","Babesiose/Ehrlichiose"],
    next:"Mit Gesamtprotein koppeln (beide hoch → Dehydratation; HKT↓ & Protein↓ → Blutverlust). Bei Anämie: Retikulozyten (regenerativ?), Blutausstrich, ggf. Coombs/Reisekrankheiten." },

  rbc: { name:"Erythrozyten", abbr:"RBC", cat:"ery", unit:"×10¹²/L", ref:{lo:5.5,hi:8.5,txt:"5,5–8,5 ×10¹²/L"},
    organs:["knochenmark","niere"], pathway:"Häm-Synthese aus Succinyl-CoA (TCA); benötigt Eisen, B12, Folat",
    meaning:"Anzahl roter Blutkörperchen. Parallel zu HKT und Hämoglobin zu bewerten.",
    high:["Dehydratation","Primäre/sekundäre Polyzythämie","Windhund (Rassenorm höher)"],
    low:["Anämie aller Ursachen","Blutverlust","Knochenmark-Suppression"],
    diseases:["Anämie","Polyzythämie","CNI"],
    next:"Indizes MCV/MCHC zur Klassifikation; Retikulozyten zur Regeneration." },

  hb: { name:"Hämoglobin", abbr:"Hb", cat:"ery", unit:"g/dL", ref:{lo:12,hi:18,txt:"12–18 g/dL"},
    organs:["knochenmark","gefaess"], pathway:"Eisen-Porphyrin (Häm) + Globin; Häm aus Succinyl-CoA + Glycin",
    meaning:"Sauerstoffbindendes Eisenprotein der Erythrozyten.",
    high:["Dehydratation","Polyzythämie"],
    low:["Anämie","Eisenmangel (chronische Blutung → mikrozytär, hypochrom)"],
    diseases:["Eisenmangelanämie","chronische GI-Blutung","Flohbefall (Welpen)"],
    next:"Bei niedrigem MCH/MCHC an Eisenmangel/chronische Blutung denken → Kot auf okkultes Blut, Eisenstatus." },

  mcv: { name:"Mittleres Erythrozytenvolumen", abbr:"MCV", cat:"ery", unit:"fL", ref:{lo:60,hi:77,txt:"60–77 fL"},
    organs:["knochenmark"], pathway:"Reifung im Knochenmark",
    meaning:"Durchschnittsgröße der Erythrozyten. Klassifiziert die Anämie (mikro-/normo-/makrozytär).",
    high:["Regeneration (junge große Zellen)","manche Pudel (Normvariante)","B12/Folatmangel (selten)"],
    low:["Eisenmangel (mikrozytär)","Portosystemischer Shunt","Akita/Shiba (Normvariante)"],
    diseases:["Eisenmangelanämie","Lebershunt"],
    next:"Mikrozytär + Hypochrom → Eisenmangel/Shunt abklären (Gallensäuren, Ammoniak, Bildgebung)." },

  mch: { name:"Hämoglobingehalt pro Erythrozyt", abbr:"MCH", cat:"ery", unit:"pg", ref:{lo:19.5,hi:25.5,txt:"19,5–25,5 pg"},
    organs:["knochenmark"], pathway:"Häm-Beladung",
    meaning:"Absolute Hämoglobinmenge je Erythrozyt.",
    high:["Lipämie/Hämolyse (Messartefakt)"],
    low:["Eisenmangel"],
    diseases:["Eisenmangelanämie"], next:"Mit MCHC/MCV zusammen lesen." },

  mchc: { name:"Mittlere Hämoglobinkonzentration", abbr:"MCHC", cat:"ery", unit:"g/dL", ref:{lo:32,hi:37,txt:"32–37 g/dL"},
    organs:["knochenmark"], pathway:"Häm-Konzentration",
    meaning:"Hämoglobin-Konzentration in den Erythrozyten.",
    high:["fast immer Artefakt: Hämolyse, Lipämie, Heinz-Körper"],
    low:["Eisenmangel (hypochrom)","starke Regeneration"],
    diseases:["Eisenmangelanämie"], next:"Hohes MCHC kritisch hinterfragen (Hämolyse-Artefakt) → Ausstrich/Probenqualität." },

  rdw: { name:"Erythrozyten-Verteilungsbreite", abbr:"RDW", cat:"ery", unit:"%", ref:{lo:11,hi:15.5,txt:"11–15,5 %"},
    organs:["knochenmark"], pathway:"Größenstreuung",
    meaning:"Streuung der Erythrozytengröße (Anisozytose).",
    high:["Regeneration","Eisenmangel (früh)","gemischte Population"],
    low:["selten klinisch relevant"],
    diseases:["regenerative Anämie"], next:"Früher Marker für Regeneration/Eisenmangel noch vor MCV-Änderung." },

  retikulozyten: { name:"Retikulozyten", abbr:"Retis", cat:"ery", unit:"×10⁹/L", ref:{lo:0,hi:80,txt:"< 60–80 ×10⁹/L (absolut)"},
    organs:["knochenmark"], pathway:"junge, noch RNA-haltige Erythrozyten",
    meaning:"Schlüsselwert bei Anämie: zeigt, ob das Knochenmark antwortet (regenerativ) oder nicht.",
    high:["Regenerative Anämie: Blutverlust oder Hämolyse (Mark arbeitet)"],
    low:["Nicht-regenerative Anämie: CNI (EPO↓), chronische Entzündung, Knochenmarkschaden, frühe Phase (<2–4 Tage)"],
    diseases:["Blutungsanämie","Hämolyse/IMHA","CNI","Knochenmarkaplasie"],
    next:"Regenerativ → Blutungs-/Hämolysequelle suchen (Ausstrich, Coombs, Bildgebung). Nicht-regenerativ → Niere, Entzündung, Knochenmark (Punktion) prüfen." },

  /* ===================== WEISSE REIHE ===================== */
  wbc: { name:"Leukozyten gesamt", abbr:"WBC", cat:"leuko", unit:"×10⁹/L", ref:{lo:6,hi:17,txt:"6–17 ×10⁹/L"},
    organs:["knochenmark","milz"], pathway:"Immunabwehr",
    meaning:"Gesamtzahl weißer Blutkörperchen. Erst das Differenzialblutbild macht den Wert interpretierbar.",
    high:["Entzündung/Infektion","Stress/Kortison","Leukämie","nach Anstrengung (Demargination)"],
    low:["Überwältigende Sepsis (Verbrauch)","Virus (Parvovirose!)","Knochenmark-Suppression","Endotoxämie"],
    diseases:["Infektion","Sepsis","Parvovirose","Leukämie"],
    next:"Immer Differenzialblutbild: welche Zellreihe? Linksverschiebung? Toxische Neutrophile? Bei Leukopenie an Parvo/Sepsis denken." },

  neutrophile: { name:"Neutrophile (segmentkernig)", abbr:"Neut", cat:"leuko", unit:"×10⁹/L", ref:{lo:3,hi:11.5,txt:"3–11,5 ×10⁹/L"},
    organs:["knochenmark"], pathway:"Bakterienabwehr (Phagozytose)",
    meaning:"Wichtigste Abwehrzellen gegen Bakterien. Reagieren auf Entzündung UND auf Stress/Kortison.",
    high:["Bakterielle Entzündung/Infektion","Stress-/Kortisonmuster","Nekrose, Immunerkrankung","Neoplasie"],
    low:["Schwere Sepsis (Verbrauch > Nachschub)","Virus","Knochenmarkschaden"],
    diseases:["Pyometra","Abszess/Peritonitis","Sepsis","Parvovirose"],
    next:"Stabkernige (Linksverschiebung) + toxische Veränderungen sprechen für echte Entzündung; reine Neutrophilie mit Lymphopenie eher Stress." },

  bands: { name:"Stabkernige Neutrophile", abbr:"Bands", cat:"leuko", unit:"×10⁹/L", ref:{lo:0,hi:0.3,txt:"< 0,3 ×10⁹/L"},
    organs:["knochenmark"], pathway:"unreife Neutrophile",
    meaning:"Unreife Neutrophile. Erhöhung = „Linksverschiebung“ – Zeichen starker, akuter Entzündung.",
    high:["Akute schwere bakterielle Entzündung (Pyometra, Peritonitis)","Sepsis (degenerative Linksverschiebung)"],
    low:["normal niedrig"],
    diseases:["Sepsis","Pyometra","schwere Infektion"],
    next:"Degenerative Linksverschiebung (mehr Stab- als Segmentkernige) ist ein Warnsignal → Fokus suchen (Bildgebung, Laktat, ggf. Notfall)." },

  lymphozyten: { name:"Lymphozyten", abbr:"Lymph", cat:"leuko", unit:"×10⁹/L", ref:{lo:1,hi:4.8,txt:"1–4,8 ×10⁹/L"},
    organs:["knochenmark","milz"], pathway:"spezifische/erworbene Immunität (Antikörper, T-Zellen)",
    meaning:"Träger der erworbenen Immunabwehr. Lymphopenie ist der zuverlässigste Stress-/Kortisonmarker.",
    high:["Chronische Antigenstimulation","junge Tiere","Lymphom/lymphatische Leukämie","Addison (fehlender Stress!)"],
    low:["Stress/Kortison (Cushing, exogenes Cortison) – häufigste Ursache","akute Virusinfektion","Lymphverlust (Chylothorax)"],
    diseases:["Lymphom","Morbus Addison","Cushing"],
    next:"Lymphozytose + Hyperkalzämie → Lymphom-Verdacht. Fehlendes Stressleukogramm bei krankem Tier → an Addison denken (Na/K, ACTH-Test)." },

  monozyten: { name:"Monozyten", abbr:"Mono", cat:"leuko", unit:"×10⁹/L", ref:{lo:0.15,hi:1.35,txt:"0,15–1,35 ×10⁹/L"},
    organs:["knochenmark"], pathway:"Gewebemakrophagen, Aufräumzellen",
    meaning:"Reagieren auf chronische Entzündung, Gewebezerfall und gehören zum Stressmuster.",
    high:["Chronische/eitrige Entzündung","Gewebenekrose","Stress/Kortison"],
    low:["selten relevant"],
    diseases:["chronischer Abszess","Pyogranulom"], next:"Mit Neutrophilen-Bild und Klinik koppeln." },

  eosinophile: { name:"Eosinophile", abbr:"Eos", cat:"leuko", unit:"×10⁹/L", ref:{lo:0.1,hi:1.25,txt:"0,1–1,25 ×10⁹/L"},
    organs:["knochenmark","darm"], pathway:"Parasiten-/Allergieabwehr (Histamin-Gegenspieler)",
    meaning:"Steigen bei Allergie und Parasiten (Haut, Darm, Atemwege).",
    high:["Parasiten (Würmer, Flöhe, Räude)","Allergie/atopische Dermatitis","Eosinophile Bronchopneumopathie/Gastroenteritis","Addison","Mastzelltumor"],
    low:["Stress/Kortison (Eosinopenie)"],
    diseases:["Parasitose","Allergie","Addison","Mastzelltumor"],
    next:"Persistierende Eosinophilie → Kot (Parasiten), Haut, Lunge prüfen; bei Begleit-Hyponatriämie/Hyperkaliämie an Addison denken." },

  basophile: { name:"Basophile", abbr:"Baso", cat:"leuko", unit:"×10⁹/L", ref:{lo:0,hi:0.1,txt:"≈ 0 ×10⁹/L (selten)"},
    organs:["knochenmark"], pathway:"Histamin/Heparin, oft mit Eosinophilie",
    meaning:"Selten erhöht; meist gemeinsam mit Eosinophilie.",
    high:["Allergie","Parasiten (Herzwurm)","Hyperlipidämie","Mastzelltumor"],
    low:["nicht relevant"],
    diseases:["Herzwurm","Allergie"], next:"Mit Eosinophilen interpretieren." },

  /* ===================== THROMBOZYTEN & GERINNUNG ===================== */
  thrombozyten: { name:"Thrombozyten (Blutplättchen)", abbr:"Thrombo", cat:"thrombo", unit:"×10⁹/L", ref:{lo:200,hi:500,txt:"200–500 ×10⁹/L"},
    organs:["knochenmark","milz"], pathway:"primäre Hämostase (Pfropfbildung)",
    meaning:"Stillen kleine Gefäßlecks. Niedrig = Blutungsneigung (Petechien).",
    high:["Reaktiv (Entzündung, Eisenmangel, nach Milzentfernung)","essenzielle Thrombozythämie (selten)"],
    low:["Verbrauch (DIC, Blutung)","Zerstörung (immun, ITP)","verminderte Bildung (Knochenmark)","Babesiose/Ehrlichiose/Anaplasmose","Cavalier: Messartefakt (Makroplättchen)"],
    diseases:["ITP","DIC","Reisekrankheiten","Knochenmarkschaden"],
    next:"Immer Ausstrich (Klumpen? Makroplättchen?). <30 ×10⁹/L → spontane Blutungsgefahr. An vektorübertragene Erreger (PCR/Serologie) denken." },

  mpv: { name:"Mittleres Thrombozytenvolumen", abbr:"MPV", cat:"thrombo", unit:"fL", ref:{lo:7,hi:13,txt:"7–13 fL"},
    organs:["knochenmark"], pathway:"Plättchengröße/Alter",
    meaning:"Große (junge) Plättchen = aktive Bildung.",
    high:["aktive Regeneration","Cavalier (Makrothrombozyten)"],
    low:["verminderte Bildung"],
    diseases:["ITP (Regeneration)"], next:"Hohes MPV bei Thrombozytopenie spricht für arbeitendes Knochenmark." },

  pt: { name:"Prothrombinzeit", abbr:"PT", cat:"thrombo", unit:"s", ref:{lo:6,hi:12,txt:"≈ 6–12 s (laborabh.)"},
    organs:["leber"], pathway:"extrinsischer + gemeinsamer Gerinnungsweg (Faktor VII)",
    meaning:"Misst den extrinsischen Weg. Verlängert sich früh bei Vitamin-K-Mangel.",
    high:["Rattengift (Cumarin) – PT verlängert sich zuerst!","Leberinsuffizienz","Vitamin-K-Mangel/Cholestase","DIC"],
    low:["nicht relevant"],
    diseases:["Rodentizidvergiftung","Leberversagen","DIC"],
    next:"Bei Blutung + verlängerter PT an Rattengift denken (Anamnese, Vitamin K₁ als Therapie/Test); aPTT, Thrombozyten, Fibrinogen ergänzen." },

  aptt: { name:"aktivierte part. Thromboplastinzeit", abbr:"aPTT", cat:"thrombo", unit:"s", ref:{lo:9,hi:18,txt:"≈ 9–18 s (laborabh.)"},
    organs:["leber"], pathway:"intrinsischer + gemeinsamer Weg (Faktoren VIII, IX, XI, XII)",
    meaning:"Misst den intrinsischen Weg.",
    high:["Hämophilie A/B","DIC","schwere Leberinsuffizienz","Rattengift (später als PT)","Heparin"],
    low:["nicht relevant"],
    diseases:["Hämophilie","DIC","Rodentizid"],
    next:"PT + aPTT zusammen einordnen; beide verlängert + Thrombozyten↓ + D-Dimer↑ → DIC." },

  fibrinogen: { name:"Fibrinogen", abbr:"Fib", cat:"thrombo", unit:"mg/dL", ref:{lo:100,hi:400,txt:"100–400 mg/dL"},
    organs:["leber"], pathway:"Gerinnungssubstrat & Akute-Phase-Protein",
    meaning:"Gerinnungsfaktor I und Entzündungsmarker.",
    high:["Entzündung (Akute-Phase)","Dehydratation"],
    low:["Verbrauch (DIC)","Leberinsuffizienz"],
    diseases:["DIC","Entzündung"], next:"Niedriges Fibrinogen bei Blutung → DIC/Leber prüfen." },

  ddimer: { name:"D-Dimere", abbr:"D-Dimer", cat:"thrombo", unit:"ng/mL", ref:{lo:0,hi:250,txt:"< 250–500 ng/mL"},
    organs:["gefaess"], pathway:"Fibrin-Abbauprodukt",
    meaning:"Zeigt Gerinnselbildung und -auflösung an (unspezifisch).",
    high:["DIC","Thromboembolie","innere Blutung/OP","Neoplasie"],
    low:["unauffällig"],
    diseases:["DIC","Thromboembolie"], next:"Im Kontext mit PT/aPTT/Thrombozyten; isoliert wenig aussagekräftig." },

  vwf: { name:"von-Willebrand-Faktor (vWF:Ag)", abbr:"vWF", cat:"thrombo", unit:"%", ref:{lo:70,hi:180,txt:"70–180 % (< 35 % Risiko)"},
    organs:["gefaess"], pathway:"Plättchenadhäsion (primäre Hämostase)",
    meaning:"Vermittelt die Anheftung der Plättchen ans Gefäß. Erblicher Mangel = häufigste Gerinnungsstörung beim Hund.",
    high:["nicht relevant"],
    low:["von-Willebrand-Erkrankung (Dobermann, Sheltie, Scottie u. a.)"],
    diseases:["von-Willebrand-Krankheit"],
    next:"Vor OP bei Risikorassen testen; bei Schleimhautblutung trotz normaler PT/aPTT/Thrombozyten an vWD denken." },

  /* ===================== LEBER & GALLE ===================== */
  alt: { name:"Alanin-Aminotransferase", abbr:"ALT", cat:"leber", unit:"U/L", ref:{lo:10,hi:100,txt:"≈ 10–100 U/L"},
    organs:["leber"], pathway:"Transaminierung (Aminosäure↔TCA), leberzellspezifisch",
    meaning:"Leberzell-spezifisches Enzym. Steigt bei Schädigung der Leberzellmembran.",
    high:["Leberzellschaden (Toxine, Medikamente, Entzündung, Hypoxie)","Lebertumor","Schwere Muskelschäden (gering)"],
    low:["ohne Bedeutung"],
    diseases:["Hepatitis","Toxische Leberschädigung (Xylit!, Pilze, Medikamente)","Leberlipidose"],
    next:"Mit ALP/GGT/Bilirubin und Gallensäuren koppeln (Schaden vs. Stau vs. Funktion). Höhe ≠ Schweregrad. Xylit-/Toxinanamnese!" },

  ast: { name:"Aspartat-Aminotransferase", abbr:"AST", cat:"leber", unit:"U/L", ref:{lo:15,hi:55,txt:"≈ 15–55 U/L"},
    organs:["leber","muskel","herz"], pathway:"Transaminierung in Leber UND Muskel",
    meaning:"Kommt in Leber und Muskel vor – weniger spezifisch als ALT.",
    high:["Leberschaden","Muskelschaden (mit CK↑)","Hämolyse (Artefakt)"],
    low:["ohne Bedeutung"],
    diseases:["Hepatopathie","Myopathie"],
    next:"AST↑ + CK↑ → Muskel; AST↑ + ALT↑ → Leber." },

  alp: { name:"Alkalische Phosphatase", abbr:"ALP/AP", cat:"leber", unit:"U/L", ref:{lo:20,hi:150,txt:"≈ 20–150 U/L (Welpen viel höher)"},
    organs:["leber","gallenwege","knochenmark"], pathway:"Cholestase-Marker; auch Knochen-Isoenzym",
    meaning:"Sensibler, aber unspezifischer Stau-/Cholestasemarker. Beim Hund auch durch Kortison induzierbar.",
    high:["Cholestase (Gallenstau)","Kortison/Cushing (steroid-induzierte ALP)","Wachstum/Knochen (Welpen, Frakturheilung)","Phenobarbital","Leberknoten (noduläre Hyperplasie alter Hunde)"],
    low:["ohne Bedeutung"],
    diseases:["Cushing-Syndrom","Cholangiohepatitis","Gallenwegsverschluss","Pankreatitis (mit Stau)"],
    next:"ALP↑ isoliert beim alten Hund oft harmlos (Hyperplasie/Steroid). Mit GGT, Bilirubin, Gallensäuren und Cushing-Test (LDDS/ACTH) abklären." },

  ggt: { name:"Gamma-Glutamyltransferase", abbr:"GGT", cat:"leber", unit:"U/L", ref:{lo:0,hi:10,txt:"0–10 U/L"},
    organs:["leber","gallenwege"], pathway:"Gallengangsepithel; Glutathion-Stoffwechsel",
    meaning:"Spezifischer für Gallenwege/Cholestase als ALP.",
    high:["Cholestase","Gallengangserkrankung","Kortison (geringer als ALP)"],
    low:["ohne Bedeutung"],
    diseases:["Cholangitis","Gallenwegsverschluss"],
    next:"GGT + ALP gemeinsam erhöht stützt Cholestase; nur ALP → eher Knochen/Steroid." },

  bilirubin: { name:"Bilirubin (gesamt)", abbr:"Bili", cat:"leber", unit:"mg/dL", ref:{lo:0,hi:0.3,txt:"0–0,3 mg/dL"},
    organs:["leber","gallenwege","milz"], pathway:"Häm-Abbau → Galle",
    meaning:"Abbauprodukt des Häms. Erhöht = Ikterus (Gelbsucht).",
    high:["Prähepatisch: Hämolyse (IMHA, Babesiose, Zwiebel/Knoblauch)","Hepatisch: Leberschaden","Posthepatisch: Gallenstau/Verschluss (Pankreatitis, Stein, Tumor)"],
    low:["ohne Bedeutung"],
    diseases:["Hämolytische Anämie","Hepatopathie","Gallengangsobstruktion"],
    next:"Mit HKT trennen: Bili↑ + Anämie + Retis↑ → Hämolyse; Bili↑ ohne Anämie → Leber/Galle (ALP/GGT, Ultraschall)." },

  gallensaeuren: { name:"Gallensäuren (nüchtern/postprandial)", abbr:"GS", cat:"leber", unit:"µmol/L", ref:{lo:0,hi:10,txt:"nüchtern < 10; 2 h nach Futter < 25–30"},
    organs:["leber","gallenwege","darm"], pathway:"enterohepatischer Kreislauf; Taurin-Konjugation (canin-spezifisch)",
    meaning:"Funktionstest der Leber. Ideal zur Shunt-Abklärung bei normalen Enzymen.",
    high:["Portosystemischer Shunt (junge Klein-/Zwergrassen, Yorkie)","Leberinsuffizienz/Zirrhose","Cholestase"],
    low:["unauffällig"],
    diseases:["Lebershunt","Leberversagen","Mikrovaskuläre Dysplasie"],
    next:"Gold-Funktionstest bei niedrigem Harnstoff/Albumin, Mikrozytose oder Krampf nach Futter → plus Ammoniak und Bildgebung (Shunt-Suche)." },

  ammoniak: { name:"Ammoniak (NH₃)", abbr:"NH₃", cat:"leber", unit:"µmol/L", ref:{lo:0,hi:60,txt:"< 60 µmol/L (laborabh.)"},
    organs:["leber","darm","gefaess"], pathway:"Harnstoffzyklus (Entgiftung); Arginin beim Hund essenziell",
    meaning:"Hochtoxisch; wird in der Leber zu Harnstoff entgiftet. Erhöht → hepatische Enzephalopathie.",
    high:["Portosystemischer Shunt","Leberversagen","Harnstoffzyklus-Defekt","Argininmangel (Diätfehler bei Katzen extrem; Hund seltener)"],
    low:["unauffällig"],
    diseases:["Hepatische Enzephalopathie","Lebershunt"],
    next:"Bei Speicheln/Krampf/Apathie nach Mahlzeit sofort messen (Probe schnell verarbeiten!) → Gallensäuren, Bildgebung. Verknüpft mit dem Harnstoffzyklus in Canis Metabolica." },

  /* ===================== NIERE & HARN ===================== */
  harnstoff: { name:"Harnstoff (BUN)", abbr:"BUN", cat:"niere", unit:"mg/dL", ref:{lo:20,hi:50,txt:"≈ 20–50 mg/dL (7–27 je Labor)"},
    organs:["niere","leber","darm"], pathway:"Endprodukt des Harnstoffzyklus; renal ausgeschieden",
    meaning:"Stickstoff-Endprodukt. Steigt bei Niereninsuffizienz, aber stark futter-/hydratationsabhängig.",
    high:["Prärenal: Dehydratation, Schock, herzbedingt","Renal: Niereninsuffizienz","Postrenal: Harnabflussstörung/Ruptur","GI-Blutung, proteinreiches Futter"],
    low:["Leberinsuffizienz/Shunt (Synthese↓)","proteinarme Diät","Polyurie/Überwässerung"],
    diseases:["CNI/AKI","Dehydratation","Urethraverschluss","Lebershunt"],
    next:"Niemals isoliert! Mit Kreatinin, SDMA, Phosphat, Kalium, Urin-spez.-Gewicht (USG) und UPC. USG zeigt prärenal (konzentriert) vs. renal (isosthenurisch)." },

  kreatinin: { name:"Kreatinin", abbr:"Krea", cat:"niere", unit:"mg/dL", ref:{lo:0.5,hi:1.5,txt:"0,5–1,5 mg/dL"},
    organs:["niere","muskel"], pathway:"Muskel-Kreatin-Abbau; glomeruläre Filtration",
    meaning:"Filtrationsmarker. Steigt aber erst, wenn ~75 % der Nephrone ausgefallen sind (späte Anzeige). Muskelmasse-abhängig.",
    high:["Niereninsuffizienz (renal)","Dehydratation/Schock (prärenal)","Harnabflussstörung (postrenal)","muskulöse/Windhunde (höher)"],
    low:["geringe Muskelmasse/Kachexie","Lebershunt","Polyurie"],
    diseases:["AKI/CNI","Dehydratation","Urethraobstruktion"],
    next:"IRIS-Stadium mit Kreatinin + SDMA + USG + UPC + Blutdruck. Verlauf wichtiger als Einzelwert. Vor Bewertung Hydratation korrigieren." },

  sdma: { name:"Symmetrisches Dimethylarginin", abbr:"SDMA", cat:"niere", unit:"µg/dL", ref:{lo:0,hi:14,txt:"0–14 µg/dL"},
    organs:["niere"], pathway:"Methylierter Arginin-Metabolit; rein renal filtriert",
    meaning:"Früher Nierenmarker – steigt bereits bei ~25–40 % Funktionsverlust, kaum muskelabhängig.",
    high:["Frühe Niereninsuffizienz (vor Kreatinin)","etablierte CNI/AKI"],
    low:["unauffällig"],
    diseases:["frühe CNI","AKI"],
    next:"Persistent >14 trotz normalem Kreatinin → frühe Nierenerkrankung: USG, UPC, Blutdruck, Verlaufskontrolle. Besonders nützlich bei alten/kachektischen Hunden." },

  phosphat: { name:"Phosphat (anorganisch)", abbr:"PO₄", cat:"niere", unit:"mg/dL", ref:{lo:2.5,hi:5.5,txt:"2,5–5,5 mg/dL (Welpen höher)"},
    organs:["niere","knochenmark"], pathway:"Knochen-/Energiestoffwechsel (ATP); renal reguliert",
    meaning:"Eng an Niere, Calcium und Knochen gekoppelt.",
    high:["Niereninsuffizienz (häufig)","Welpen/Wachstum (physiologisch)","Zellzerfall/Tumorlyse","Vitamin-D-Überdosis","Hypoparathyreoidismus"],
    low:["Hyperparathyreoidismus","Tumor-Hyperkalzämie","Insulin/Glukose-Therapie (DKA-Behandlung)"],
    diseases:["renaler sekundärer Hyperparathyreoidismus","CNI"],
    next:"Hohes Phosphat treibt bei CNI den Knochenstoffwechsel (Phosphatbinder/Diät). Mit Calcium (Ca×P-Produkt) und Nierenwerten bewerten." },

  usg: { name:"Urin-spezifisches Gewicht", abbr:"USG", cat:"niere", unit:"", ref:{lo:1.015,hi:1.045,txt:"> 1,030 = gut konzentriert"},
    organs:["niere"], pathway:"Konzentrationsfähigkeit der Niere",
    meaning:"Zeigt, ob die Niere Urin konzentrieren kann – entscheidend zur Einordnung erhöhter Nierenwerte.",
    high:["Dehydratation mit intakter Niere (>1,030 → prärenal)"],
    low:["Niereninsuffizienz (isosthenurisch 1,008–1,012 trotz Azotämie = renal)","Diabetes insipidus","Cushing","Pyometra","Diurese/Infusion"],
    diseases:["CNI","Diabetes insipidus","Cushing"],
    next:"IMMER zusammen mit Harnstoff/Kreatinin abnehmen (vor Infusion!). Azotämie + verdünnter Urin = renal; Azotämie + konzentrierter Urin = prärenal (Dehydratation)." },

  upc: { name:"Protein/Kreatinin im Urin", abbr:"UPC", cat:"niere", unit:"", ref:{lo:0,hi:0.2,txt:"< 0,2 normal; 0,2–0,5 fraglich; > 0,5 Proteinurie"},
    organs:["niere"], pathway:"glomeruläre/tubuläre Eiweißverluste",
    meaning:"Quantifiziert renalen Eiweißverlust.",
    high:["Glomerulonephritis","Leishmaniose, Amyloidose","Hypertonie","Lyme-Nephritis"],
    low:["unauffällig"],
    diseases:["Protein-Losing-Nephropathy","Leishmaniose","Amyloidose"],
    next:"Erst Harnsediment/Infekt ausschließen, dann UPC. Persistente Proteinurie → Blutdruck, Leishmaniose-Test (Reiseanamnese), Albumin." },

  /* ===================== ELEKTROLYTE & SÄURE-BASEN ===================== */
  natrium: { name:"Natrium (Na⁺)", abbr:"Na", cat:"elektro", unit:"mmol/L", ref:{lo:144,hi:160,txt:"144–160 mmol/L"},
    organs:["niere","nebenniere","gefaess"], pathway:"Wasserhaushalt, osmotischer Hauptkation",
    meaning:"Leitkation des Wasserhaushalts; eng an Volumen und ADH/Aldosteron gekoppelt.",
    high:["Wasserverlust > Salzverlust (Durchfall, Hecheln, Hitze)","mangelnde Wasseraufnahme","Diabetes insipidus","Salzaufnahme"],
    low:["Verlust (Erbrechen/Durchfall)","Morbus Addison (Aldosteron↓)","Herz-/Leber-/Nierenödeme","Pleural-/Aszitesergüsse"],
    diseases:["Morbus Addison","Dehydratation","Diabetes insipidus"],
    next:"Mit Kalium als Na/K-Quotient: <27 → Addison-Verdacht (ACTH-Stimulationstest). Korrektur immer langsam (Hirnödem-Gefahr)." },

  kalium: { name:"Kalium (K⁺)", abbr:"K", cat:"elektro", unit:"mmol/L", ref:{lo:3.5,hi:5.5,txt:"3,5–5,5 mmol/L"},
    organs:["niere","nebenniere","herz"], pathway:"Membranpotenzial (Herz/Nerv); Aldosteron-reguliert",
    meaning:"Bestimmt die elektrische Erregbarkeit von Herz und Muskel. Lebensbedrohlich bei starker Abweichung.",
    high:["Harnabflussstörung/Urethraverschluss (Notfall!)","Anurie/AKI","Morbus Addison","Ruptur Harnblase","Akita/Hämolyse (Pseudohyperkaliämie)"],
    low:["Erbrechen/Durchfall","Anorexie","Diurese/Infusion ohne K","Cushing/Steroide","DKA-Insulintherapie"],
    diseases:["Morbus Addison","Urethraobstruktion","AKI","chron. GI-Verluste"],
    next:"Hohes K + niedriges Na + Bradykardie → EKG (Notfall) und Addison/Obstruktion abklären (Blase scannen!). Probe nicht hämolytisch?" },

  chlorid: { name:"Chlorid (Cl⁻)", abbr:"Cl", cat:"elektro", unit:"mmol/L", ref:{lo:109,hi:122,txt:"109–122 mmol/L"},
    organs:["niere","darm"], pathway:"Säure-Basen-Haushalt, folgt meist dem Natrium",
    meaning:"Folgt überwiegend dem Natrium; wichtig für Säure-Basen-Bewertung.",
    high:["Dehydratation","metabolische Azidose","renal-tubuläre Azidose"],
    low:["Erbrechen von Magensäure (HCl-Verlust → metabolische Alkalose)","Diuretika"],
    diseases:["Pylorusobstruktion","metabolische Azidose/Alkalose"],
    next:"Korrigiertes Chlorid (zu Na) berechnen; isolierter Cl-Verlust bei Erbrechen → Alkalose." },

  bicarbonat: { name:"Bicarbonat (HCO₃⁻/TCO₂)", abbr:"HCO₃", cat:"elektro", unit:"mmol/L", ref:{lo:17,hi:25,txt:"17–25 mmol/L"},
    organs:["niere","gefaess"], pathway:"Puffer des Säure-Basen-Haushalts",
    meaning:"Wichtigster Blutpuffer.",
    high:["metabolische Alkalose (Erbrechen)"],
    low:["metabolische Azidose (Schock, Laktat, Ketose/DKA, Niereninsuffizienz, Vergiftung)"],
    diseases:["DKA","Schock/Laktatazidose","CNI"],
    next:"Mit Anionenlücke und Laktat zusammen lesen; niedriges HCO₃ + hohe Anionenlücke → organische Säure (Laktat, Ketone)." },

  anionenluecke: { name:"Anionenlücke", abbr:"AG", cat:"elektro", unit:"mmol/L", ref:{lo:12,hi:24,txt:"12–24 mmol/L"},
    organs:["niere","gefaess"], pathway:"rechnerisch (Na+K) − (Cl+HCO₃)",
    meaning:"Deckt unmessbare Säuren auf.",
    high:["Laktatazidose (Schock)","Ketoazidose (DKA)","Urämie","Ethylenglykol-/Salicylatvergiftung"],
    low:["Hypoalbuminämie","Laborfehler"],
    diseases:["DKA","Laktatazidose","Ethylenglykolvergiftung"],
    next:"Hohe Anionenlücke → Laktat, Ketone, Nierenwerte, Toxinanamnese (Frostschutz!) prüfen." },

  calcium: { name:"Calcium (gesamt / ionisiert)", abbr:"Ca", cat:"elektro", unit:"mg/dL", ref:{lo:9.5,hi:11.5,txt:"gesamt 9,5–11,5; ionisiert 1,25–1,45 mmol/L"},
    organs:["niere","knochenmark","darm"], pathway:"Knochen, Muskel-/Nervenfunktion, Gerinnung; PTH/Vit-D-reguliert",
    meaning:"Streng reguliert durch Nebenschilddrüse und Vitamin D; an Albumin gebunden.",
    high:["Tumor (Lymphom, Analbeutel-Adenokarzinom → 'Hyperkalzämie der Malignität')","primärer Hyperparathyreoidismus","Vitamin-D-Intoxikation (Rodentizid, Psoriasiscreme)","Morbus Addison","CNI"],
    low:["Eklampsie (laktierende kleine Hündin)","Hypoparathyreoidismus","akute Pankreatitis","Ethylenglykol","Hypoalbuminämie (scheinbar)"],
    diseases:["Hyperkalzämie der Malignität","Eklampsie","Hypoparathyreoidismus"],
    next:"Immer ionisiertes Calcium messen (aussagekräftiger) und ggf. um Albumin korrigieren. Persistente Hyperkalzämie → Tumorsuche + PTH/PTHrP. Krämpfe/Zittern → niedriges Ca prüfen." },

  magnesium: { name:"Magnesium (Mg²⁺)", abbr:"Mg", cat:"elektro", unit:"mg/dL", ref:{lo:1.5,hi:2.5,txt:"1,5–2,5 mg/dL"},
    organs:["niere","muskel","herz"], pathway:"Enzym-Cofaktor (ATP), Muskel/Nerv",
    meaning:"Cofaktor vieler Enzyme; oft mit Kalium/Calcium gestört.",
    high:["Niereninsuffizienz","Übersupplementierung"],
    low:["GI-Verluste, Diurese, Diabetes, kritisch Kranke"],
    diseases:["refraktäre Hypokaliämie/-kalzämie"],
    next:"Bei therapieresistenter Hypokaliämie/Hypokalzämie an Magnesiummangel denken." },

  /* ===================== PROTEINE ===================== */
  gesamtprotein: { name:"Gesamtprotein (TP)", abbr:"TP", cat:"protein", unit:"g/dL", ref:{lo:5.4,hi:7.5,txt:"5,4–7,5 g/dL"},
    organs:["leber","darm","niere","gefaess"], pathway:"Albumin + Globuline; Onkotischer Druck",
    meaning:"Summe aus Albumin und Globulinen. Mit HKT der Schlüssel zur Hydratationsbewertung.",
    high:["Dehydratation (mit HKT↑)","Hyperglobulinämie (chronische Entzündung, Leishmaniose, Myelom)"],
    low:["Blutverlust","Protein-Losing-Enteropathy/-Nephropathy","Leberinsuffizienz","Exsudation/Verbrennung"],
    diseases:["Dehydratation","PLE/PLN","Leishmaniose","multiples Myelom"],
    next:"Albumin und Globulin getrennt betrachten (Elektrophorese bei Hyperglobulinämie). TP↑ + HKT↑ = Eindickung." },

  albumin: { name:"Albumin", abbr:"Alb", cat:"protein", unit:"g/dL", ref:{lo:2.7,hi:4.0,txt:"2,7–4,0 g/dL"},
    organs:["leber","darm","niere"], pathway:"in der Leber synthetisiert; Onkotik & Transport",
    meaning:"Wichtigstes Transport- und Onkotik-Protein; nur in der Leber gebildet.",
    high:["Dehydratation (relativ)"],
    low:["Leberinsuffizienz (Synthese↓)","Protein-Losing-Enteropathy (Darm)","Protein-Losing-Nephropathy (Niere, UPC↑)","Entzündung (negatives Akute-Phase-Protein)","Blutung/Exsudation"],
    diseases:["PLE (z. B. Lymphangiektasie)","PLN","Leberzirrhose","schwere Entzündung"],
    next:"Niedriges Albumin → ist Globulin mit niedrig (Verlust Darm/Blut) oder normal/hoch (Leber/Niere)? → UPC, Gallensäuren, Darmpanel (Cobalamin/Folat), Bildgebung. <1,5 g/dL → Ödem-/Erguss-Gefahr." },

  globulin: { name:"Globuline", abbr:"Glob", cat:"protein", unit:"g/dL", ref:{lo:2.0,hi:4.0,txt:"2,0–4,0 g/dL"},
    organs:["leber","milz"], pathway:"Antikörper (γ) & Transportproteine (α,β)",
    meaning:"Umfassen Antikörper und Akute-Phase-Proteine.",
    high:["Chronische Infektion/Entzündung","Leishmaniose, Ehrlichiose (polyklonal)","multiples Myelom (monoklonal)"],
    low:["Verlust (Darm/Blutung)","Immundefekt/Welpe (vor Kolostrum)"],
    diseases:["Leishmaniose","Ehrlichiose","Myelom","PLE"],
    next:"Hyperglobulinämie → Serum-Elektrophorese (poly- vs. monoklonal); monoklonal → Myelom/Ehrlichiose abklären." },

  agratio: { name:"Albumin/Globulin-Quotient", abbr:"A/G", cat:"protein", unit:"", ref:{lo:0.6,hi:1.1,txt:"≈ 0,6–1,1"},
    organs:["leber","darm"], pathway:"Verhältnis Albumin:Globulin",
    meaning:"Mustererkennung: zeigt, ob Albumin und Globulin gleich- oder gegenläufig verändert sind.",
    high:["selten (Globulinmangel)"],
    low:["Albumin↓ und/oder Globulin↑ (Entzündung, Leishmaniose, Myelom, Verlust)"],
    diseases:["chronische Entzündung","PLE (beide ↓ → A/G ~normal)"],
    next:"Niedriger A/G → Elektrophorese. Beide Fraktionen ↓ (A/G normal) → Verlust über Darm/Blut." },

  /* ===================== ZUCKER & FETT ===================== */
  glucose: { name:"Glucose (Blutzucker)", abbr:"Glu", cat:"stoff", unit:"mg/dL", unitSI:"3,9–6,7 mmol/L", ref:{lo:70,hi:120,txt:"70–120 mg/dL"},
    organs:["pankreas","leber","nebenniere"], pathway:"Glykolyse/Gluconeogenese; Insulin↓ Glukagon↑",
    formula:"C₆H₁₂O₆",
    meaning:"Energieträger; durch Insulin/Glukagon eng geregelt. Verknüpft mit der Glykolyse in Canis Metabolica.",
    high:["Diabetes mellitus","Stress (v. a. nach Aufregung, weniger ausgeprägt als bei Katze)","Cushing","Glukose-Infusion","postprandial"],
    low:["Welpen/Toy-Rassen (Reserven klein)","Insulinom","Sepsis","Leberversagen/Shunt","Addison","Insulin-Überdosis","Xylit-Vergiftung (Notfall!)","Probenfehler (verzögerte Trennung)"],
    diseases:["Diabetes mellitus","Insulinom","Sepsis","Xylit-Intoxikation"],
    next:"Persistierende Hyperglykämie → Fruktosamin (echter DM?) + Urinzucker. Hypoglykämie → Ursache nach Alter: Welpe (Reserve) vs. Insulinom (Insulin/Glukose-Ratio) vs. Xylit-Anamnese." },

  fruktosamin: { name:"Fruktosamin", abbr:"FAM", cat:"stoff", unit:"µmol/L", ref:{lo:200,hi:350,txt:"200–350 µmol/L"},
    organs:["pankreas","gefaess"], pathway:"glykiertes Protein (Langzeit-Zucker ~2–3 Wo.)",
    meaning:"Langzeitwert des Blutzuckers – unbeeinflusst von akutem Stress.",
    high:["Diabetes mellitus (bestätigt anhaltende Hyperglykämie)"],
    low:["Hypoglykämie über Tage","Hypoproteinämie/Hyperthyreose (verfälscht)"],
    diseases:["Diabetes mellitus"],
    next:"Trennt echten Diabetes von Stresshyperglykämie und kontrolliert die Insulineinstellung." },

  cholesterin: { name:"Cholesterin", abbr:"Chol", cat:"stoff", unit:"mg/dL", ref:{lo:130,hi:350,txt:"130–350 mg/dL"},
    organs:["leber","schilddruese","gallenwege"], pathway:"Lipidstoffwechsel; Steroid-/Gallensäure-Vorstufe",
    meaning:"Spiegelt Fettstoffwechsel und mehrere Hormonachsen wider.",
    high:["Hypothyreose (klassisch!)","Cushing","Diabetes mellitus","Cholestase","nephrotisches Syndrom","postprandial/Hyperlipidämie (Schnauzer)"],
    low:["Leberinsuffizienz/Shunt","Protein-Losing-Enteropathy","Maldigestion"],
    diseases:["Hypothyreose","Cushing","nephrotisches Syndrom"],
    next:"Hohes Cholesterin + Lethargie/Gewichtszunahme + niedrige T4 → Schilddrüse (T4/fT4/TSH) testen. Nüchtern abnehmen." },

  triglyceride: { name:"Triglyceride", abbr:"TG", cat:"stoff", unit:"mg/dL", ref:{lo:20,hi:150,txt:"20–150 mg/dL (nüchtern)"},
    organs:["leber","pankreas"], pathway:"Neutralfette; β-Oxidation/Lipolyse",
    meaning:"Neutralfette; nüchtern messen.",
    high:["nicht-nüchtern","primäre Hyperlipidämie (Zwergschnauzer, Sheltie)","Hypothyreose, Cushing, Diabetes","Pankreatitis-Risiko/-folge"],
    low:["selten relevant"],
    diseases:["idiopathische Hyperlipidämie","Pankreatitis"],
    next:"Anhaltende Hypertriglyceridämie → Pankreatitis-Risiko; Grunderkrankung (Schilddrüse/Cushing) und fettarme Diät." },

  /* ===================== MUSKEL/PANKREAS-ENZYME ===================== */
  ck: { name:"Kreatinkinase", abbr:"CK", cat:"enzym", unit:"U/L", ref:{lo:50,hi:400,txt:"≈ 50–400 U/L"},
    organs:["muskel","herz"], pathway:"Muskel-Energiestoffwechsel (Kreatinphosphat↔ATP)",
    meaning:"Sehr muskelspezifisch; steigt schnell bei Muskelschaden.",
    high:["Muskeltrauma/Sturz, Injektion, langes Liegen","Krampfanfall, intensive Belastung","Myositis/Myopathie","Herzschaden"],
    low:["ohne Bedeutung"],
    diseases:["Myopathie","Trauma","Krampfgeschehen"],
    next:"CK↑ + AST↑ ohne ALP/Bili → Muskel statt Leber. Stark erhöht bei festliegenden Tieren." },

  amylase: { name:"Amylase", abbr:"Amy", cat:"enzym", unit:"U/L", ref:{lo:300,hi:1100,txt:"≈ 300–1100 U/L"},
    organs:["pankreas","niere","darm"], pathway:"Kohlenhydratverdauung",
    meaning:"Unspezifisch beim Hund – auch durch Niere/Darm beeinflusst.",
    high:["Pankreatitis (unspezifisch)","Niereninsuffizienz (verminderte Clearance)","GI-Erkrankung"],
    low:["ohne Bedeutung"],
    diseases:["Pankreatitis","CNI"],
    next:"Allein nicht beweisend – bei Pankreatitisverdacht spezifische Lipase (Spec cPL/DGGR) + Ultraschall." },

  lipase: { name:"Lipase (DGGR / Spec cPL)", abbr:"Lip", cat:"enzym", unit:"µg/L", ref:{lo:0,hi:200,txt:"Spec cPL < 200 normal; > 400 vereinbar mit Pankreatitis"},
    organs:["pankreas"], pathway:"Fettverdauung",
    meaning:"Pankreas-spezifischer als Amylase. Spec cPL/DGGR-Lipase sind die klinisch nützlichen Tests.",
    high:["Pankreatitis","(geringer) Niereninsuffizienz, GI, Steroide"],
    low:["ohne Bedeutung"],
    diseases:["akute/chronische Pankreatitis"],
    next:"Spec cPL > 400 + Klinik (Erbrechen, Bauchschmerz) + Ultraschall = Pankreatitis. Grauzone 200–400 → Verlauf/SNAP-Test." },

  /* ===================== HORMONE ===================== */
  t4: { name:"Gesamt-Thyroxin (T4)", abbr:"T4", cat:"endokrin", unit:"µg/dL", unitSI:"13–52 nmol/L", ref:{lo:1.0,hi:4.0,txt:"1,0–4,0 µg/dL"},
    organs:["schilddruese"], pathway:"Grundumsatz/Stoffwechselrate; Regelkreis mit TSH",
    meaning:"Schilddrüsenhormon, steuert den Energieumsatz. Hypothyreose ist beim Hund häufig.",
    high:["selten (Schilddrüsentumor)","Supplementierungs-Überdosis","Autoantikörper (Messartefakt)"],
    low:["Hypothyreose","Euthyroid-Sick (andere Krankheit drückt T4!)","Windhund (Rassenorm niedriger)","Medikamente (Steroide, Phenobarbital)"],
    diseases:["Hypothyreose","Euthyroid-Sick-Syndrom"],
    next:"Niedriges T4 NICHT allein bewerten: fT4 + cTSH ergänzen und schwere Begleiterkrankungen ausschließen (Euthyroid Sick). Klinik (Fell, Gewicht, Lethargie) entscheidend." },

  ft4: { name:"Freies T4 (fT4)", abbr:"fT4", cat:"endokrin", unit:"ng/dL", ref:{lo:0.6,hi:3.7,txt:"0,6–3,7 ng/dL"},
    organs:["schilddruese"], pathway:"biologisch aktiver T4-Anteil",
    meaning:"Aktiver, ungebundener Hormonanteil; weniger durch Begleitkrankheit verfälscht.",
    high:["selten"],
    low:["Hypothyreose (zusammen mit TSH↑)"],
    diseases:["Hypothyreose"],
    next:"fT4 (Gleichgewichtsdialyse) + cTSH bestätigen die Hypothyreose, wenn Gesamt-T4 grenzwertig ist." },

  tsh: { name:"Thyreoidea-stimulierendes Hormon", abbr:"cTSH", cat:"endokrin", unit:"ng/mL", ref:{lo:0,hi:0.5,txt:"0,0–0,5 ng/mL"},
    organs:["schilddruese"], pathway:"Hypophysen-Steuerhormon der Schilddrüse",
    meaning:"Steigt, wenn die Schilddrüse zu wenig produziert (Rückkopplung).",
    high:["primäre Hypothyreose (mit T4/fT4↓)"],
    low:["normal oder Euthyroid Sick"],
    diseases:["Hypothyreose"],
    next:"Klassische Hypothyreose = T4↓ + fT4↓ + TSH↑. TSH allein ist nicht beweisend (kann bei Hypothyreose normal bleiben)." },

  cortisol: { name:"Cortisol (basal & Stimulations-/Suppressionstests)", abbr:"Cort", cat:"endokrin", unit:"µg/dL", ref:{lo:1,hi:6,txt:"basal 1–6; Testprotokolle entscheiden"},
    organs:["nebenniere"], pathway:"Stresshormon; Glukose↑, immunsuppressiv",
    meaning:"Stresshormon der Nebenniere. Basalwert allein diagnostiziert WEDER Cushing NOCH Addison – Funktionstests nötig.",
    high:["Cushing (Hyperadrenokortizismus)","Stress","exogene Steroide"],
    low:["Morbus Addison (Hypoadrenokortizismus)"],
    diseases:["Cushing-Syndrom","Morbus Addison"],
    next:"Cushing-Verdacht (PU/PD, Hängebauch, ALP↑) → LDDS- oder ACTH-Stimulationstest. Addison-Verdacht (Na/K↓-Quotient, Kollaps, kein Stressleukogramm) → ACTH-Stimulationstest." },

  /* ===================== ENTZÜNDUNG & SPEZIAL ===================== */
  crp: { name:"C-reaktives Protein", abbr:"CRP", cat:"spezial", unit:"mg/L", ref:{lo:0,hi:10,txt:"< 10–20 mg/L (laborabh.)"},
    organs:["leber"], pathway:"Akute-Phase-Protein (in der Leber gebildet)",
    meaning:"Schneller, sensibler Entzündungsmarker beim Hund; gut zur Verlaufskontrolle.",
    high:["Bakterielle/systemische Entzündung","Pankreatitis","Polyarthritis, Immunerkrankung","postoperativ"],
    low:["unauffällig/Heilung"],
    diseases:["Sepsis","Pankreatitis","immunmediierte Polyarthritis"],
    next:"Sinkendes CRP zeigt Therapieerfolg. Hohes CRP unspezifisch → Fokus mit Bildgebung/Blutbild suchen." },

  laktat: { name:"Laktat", abbr:"Lac", cat:"spezial", unit:"mmol/L", ref:{lo:0,hi:2.5,txt:"< 2,0–2,5 mmol/L"},
    organs:["muskel","gefaess","leber"], pathway:"anaerobe Glykolyse (Cori-Zyklus); Perfusionsmarker",
    formula:"C₃H₆O₃",
    meaning:"Steigt bei Sauerstoff-/Durchblutungsmangel – wichtigster Schock- und Perfusionsmarker.",
    high:["Schock/Hypoperfusion","Sepsis","Magendrehung (GDV)","schwere Anämie","Krampf/Anstrengung","Lebersversagen (Clearance↓)"],
    low:["unauffällig"],
    diseases:["Schock","GDV (Magendrehung)","Sepsis"],
    next:"Hohes Laktat = Gewebe-Sauerstoffmangel → Volumen/Schocktherapie; fallendes Laktat unter Therapie ist ein gutes Prognosezeichen (z. B. bei GDV)." }
};

/* ---------- LEITBEFUND-MUSTER (Diagnose-Entscheidungshilfe) ---------- */
/* pattern[]: {label, dir:'up'|'down'|'var', param} ; */
const PATTERNS = {
  anaemie: { name:"Anämie", color:"#ff4d4d", icon:"🩸",
    summary:"Zu wenig rote Blutkörperchen. Entscheidend ist: Reagiert das Knochenmark (Retikulozyten)?",
    findings:[{p:"hkt",dir:"down"},{p:"rbc",dir:"down"},{p:"hb",dir:"down"},{p:"retikulozyten",dir:"var"}],
    decisive:"Retikulozyten: HOCH = regenerativ (Blutverlust/Hämolyse) · NIEDRIG = nicht-regenerativ (Niere, Entzündung, Knochenmark).",
    next:"Regenerativ → Blutung (Kot/okkultes Blut, Bildgebung) vs. Hämolyse (Bilirubin↑, Coombs, Babesien-PCR). Nicht-regenerativ → Niere (SDMA/Krea), Entzündung (CRP), Knochenmarkpunktion." },
  dehydratation: { name:"Dehydratation / Eindickung", color:"#00e5ff", icon:"💧",
    summary:"Wasserverlust dickt das Blut ein – viele Werte steigen scheinbar.",
    findings:[{p:"hkt",dir:"up"},{p:"gesamtprotein",dir:"up"},{p:"albumin",dir:"up"},{p:"harnstoff",dir:"up"},{p:"usg",dir:"up"}],
    decisive:"HKT UND Gesamtprotein gemeinsam erhöht, Urin konzentriert (USG > 1,030).",
    next:"Vor Infusion Urin abnehmen! Prärenale Azotämie bestätigt sich, wenn Nierenwerte nach Rehydratation normalisieren." },
  niere: { name:"Nierenerkrankung (Azotämie)", color:"#00ff87", icon:"🫘",
    summary:"Erhöhte Nierenwerte – prärenal (Dehydratation), renal oder postrenal (Abfluss)?",
    findings:[{p:"harnstoff",dir:"up"},{p:"kreatinin",dir:"up"},{p:"sdma",dir:"up"},{p:"phosphat",dir:"up"},{p:"kalium",dir:"var"},{p:"usg",dir:"down"}],
    decisive:"Azotämie + schlecht konzentrierter Urin (isosthenurisch 1,008–1,012) = renal. Azotämie + konzentrierter Urin = prärenal.",
    next:"USG (vor Infusion!), UPC, Blutdruck, Kalium/EKG, Blasen-Scan (Obstruktion?). IRIS-Staging und Verlauf." },
  leber: { name:"Leber & Cholestase", color:"#ffd166", icon:"🟡",
    summary:"Leberzellschaden vs. Gallenstau vs. Funktionsverlust unterscheiden.",
    findings:[{p:"alt",dir:"up"},{p:"alp",dir:"up"},{p:"ggt",dir:"up"},{p:"bilirubin",dir:"up"},{p:"gallensaeuren",dir:"up"},{p:"albumin",dir:"down"}],
    decisive:"ALT↑ = Zellschaden · ALP/GGT↑ = Cholestase · Gallensäuren↑ / Albumin↓ / Harnstoff↓ = Funktionsverlust.",
    next:"Gallensäuren-Stimulationstest, Ammoniak, Gerinnung (PT/aPTT), Ultraschall; Toxin-/Medikamentenanamnese (Xylit!)." },
  entzuendung: { name:"Entzündung / Infektion", color:"#00f2fe", icon:"🔥",
    summary:"Aktivierte Abwehr – bakteriell, viral oder immunmediiert?",
    findings:[{p:"wbc",dir:"var"},{p:"neutrophile",dir:"up"},{p:"bands",dir:"up"},{p:"monozyten",dir:"up"},{p:"crp",dir:"up"},{p:"globulin",dir:"up"}],
    decisive:"Neutrophilie + Linksverschiebung (Stabkernige) + toxische Zellen + CRP↑ = aktive Entzündung. Leukopenie → Sepsis/Virus.",
    next:"Fokus suchen (Bildgebung, Urin, Zytologie); bei Leukopenie an Parvovirose/Sepsis denken; Reisekrankheiten je nach Region." },
  stress: { name:"Stress / Kortison-Muster", color:"#ffa6c9", icon:"⚡",
    summary:"Endogener oder exogener Cortisol-Effekt – nicht mit Entzündung verwechseln.",
    findings:[{p:"neutrophile",dir:"up"},{p:"lymphozyten",dir:"down"},{p:"monozyten",dir:"up"},{p:"eosinophile",dir:"down"},{p:"glucose",dir:"up"},{p:"alp",dir:"up"}],
    decisive:"Reife Neutrophilie + LYMPHOPENIE + Eosinopenie (± Monozytose) ohne Linksverschiebung = klassisches Stressleukogramm.",
    next:"Bei zusätzlich PU/PD, ALP↑, Cholesterin↑ → Cushing testen (LDDS/ACTH). Fehlt das Stressmuster beim kranken Tier → Addison bedenken." },
  blutung: { name:"Blutungsneigung / Gerinnung", color:"#f35588", icon:"🩹",
    summary:"Plättchenproblem (Petechien) oder Faktorenproblem (große Blutungen)?",
    findings:[{p:"thrombozyten",dir:"down"},{p:"pt",dir:"up"},{p:"aptt",dir:"up"},{p:"fibrinogen",dir:"var"},{p:"vwf",dir:"down"},{p:"ddimer",dir:"up"}],
    decisive:"Petechien/Schleimhautblutung → primär (Thrombozyten/vWF). Hämatome/Körperhöhlenblutung + PT/aPTT↑ → sekundär (Faktoren/Rattengift).",
    next:"Ausstrich (Plättchen echt niedrig?), PT/aPTT, vWF bei Risikorasse; PT zuerst verlängert + Anamnese → Rattengift (Vitamin K₁). Alles auffällig → DIC." },
  endokrin: { name:"Hormon-Achsen (Schilddrüse/Cushing/Addison/Diabetes)", color:"#9d4edd", icon:"🧬",
    summary:"Häufige endokrine Muster auf einen Blick.",
    findings:[{p:"glucose",dir:"var"},{p:"cholesterin",dir:"up"},{p:"t4",dir:"down"},{p:"tsh",dir:"up"},{p:"alp",dir:"up"},{p:"natrium",dir:"var"},{p:"kalium",dir:"var"}],
    decisive:"Hypothyreose: Chol↑, T4↓, TSH↑. Cushing: ALP↑, Chol↑, Glu↑, Lymphopenie, USG↓. Addison: Na↓/K↑ (Quotient <27). Diabetes: Glu↑ + Fruktosamin↑ + Glukosurie.",
    next:"Gezielter Bestätigungstest: T4/fT4/TSH · ACTH-Stim oder LDDS · Na/K + ACTH-Stim · Fruktosamin/Urinzucker." }
};

/* Export für app.js (globaler Scope) */
window.HAEM = { CATEGORIES, ORGANS, BREEDS, REGION_NOTE, PARAMS, PATTERNS };
